workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter packages pub get
      - name: Update CocoaPods and install dependencies
        script: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          pod deintegrate
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 