workflows:
  ios-basic:
    name: iOS Basic Build (No Code Signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app (unsigned)
        script: |
          # Build without code signing for testing
          flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner-unsigned.ipa Payload/
    artifacts:
      - Runner-unsigned.ipa
      - build/ios/iphoneos/Runner.app
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true