// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpc9Uo-bZi3eer8Ip74l2Je0pjbznk6I',
    appId: '1:167788515229:web:4000aeed561a58fb90e974',
    messagingSenderId: '167788515229',
    projectId: 'foodapp-94323',
    authDomain: 'foodapp-94323.firebaseapp.com',
    storageBucket: 'foodapp-94323.firebasestorage.app',
    measurementId: 'G-WBNNS4586R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbyg1aBQe_jELXU0qc_gT373hnbtS52BU',
    appId: '1:167788515229:android:766c0f82a4ebd15990e974',
    messagingSenderId: '167788515229',
    projectId: 'foodapp-94323',
    storageBucket: 'foodapp-94323.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHlSO2qGN6OwM28-zjXzdJze-Oo0hJLU',
    appId: '1:167788515229:ios:8734162a8aedea4e90e974',
    messagingSenderId: '167788515229',
    projectId: 'foodapp-94323',
    storageBucket: 'foodapp-94323.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHlSO2qGN6OwM28-zjXzdJze-Oo0hJLU',
    appId: '1:167788515229:ios:8734162a8aedea4e90e974',
    messagingSenderId: '167788515229',
    projectId: 'foodapp-94323',
    storageBucket: 'foodapp-94323.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEpc9Uo-bZi3eer8Ip74l2Je0pjbznk6I',
    appId: '1:167788515229:web:f9af7d99b31c1dea90e974',
    messagingSenderId: '167788515229',
    projectId: 'foodapp-94323',
    authDomain: 'foodapp-94323.firebaseapp.com',
    storageBucket: 'foodapp-94323.firebasestorage.app',
    measurementId: 'G-P1PC8VZSS8',
  );

}